DROP TABLE IF EXISTS BOOKING;
CREATE TABLE BOOKING
(
    BOOKING_ID   UUID PRIMARY KEY,
    BOOKING_DATE DATE NOT NULL,
    BOOKED_ON    DATE NOT NULL,
    ORDER_ID     UUID NULL,
    FEEDBACK     VARCHAR NULL,
    PAYMENT_MODE VARCHAR NULL
);
